// Pre-seeded WMS Stock Opname Database — PT Unison Industrial Indonesia
// Data disinkronkan dengan tabel `user_produksi` & `item` di database MySQL `produksi`

export const WAREHOUSES = [
  { id: 1, code: 'U2 GUDANG1', name: 'Gudang U2 - Unit 1', zone: 'Fastener Finishing & Packing', default_printer_id: 1, total_racks: 24, is_active: true },
  { id: 2, code: 'U2 GUDANG2', name: 'Gudang U2 - Unit 2', zone: 'Mur & Hex Nut Storage', default_printer_id: 1, total_racks: 36, is_active: true },
  { id: 3, code: 'U2 GUDANG3', name: 'Gudang U2 - Unit 3', zone: 'Baut Hex & Socket Stock', default_printer_id: 2, total_racks: 40, is_active: true },
  { id: 4, code: 'U2 GUDANG4', name: 'Gudang U2 - Unit 4', zone: 'Stainless Steel (SS304/SS316)', default_printer_id: 2, total_racks: 28, is_active: true },
  { id: 5, code: 'U2 GUDANG5', name: 'Gudang U2 - Unit 5', zone: 'Plating & Galvanizing Stock', default_printer_id: 2, total_racks: 30, is_active: true },
  { id: 6, code: 'U2 GUDANG6', name: 'Gudang U2 - Unit 6', zone: 'Heavy Stock & Bulk Packaging (Peti)', default_printer_id: 3, total_racks: 48, is_active: true },
  { id: 7, code: 'U2 F29', name: 'Gudang U2 - Fasilitas 29', zone: 'Machining & Special Thread Tapping', default_printer_id: 3, total_racks: 16, is_active: true },
  { id: 8, code: 'U2 UCP', name: 'Gudang U2 - UCP', zone: 'Central Staging & Quality Control (QC)', default_printer_id: 1, total_racks: 20, is_active: true },
  { id: 9, code: 'GUDANG JAYA', name: 'Gudang Jaya', zone: 'Logistik & Distribusi Pengiriman Utama', default_printer_id: 4, total_racks: 50, is_active: true },
  { id: 10, code: 'D30', name: 'Gudang D30', zone: 'Raw Materials & Wire Rod Coils', default_printer_id: 3, total_racks: 12, is_active: true },
  { id: 11, code: 'U1', name: 'Gudang U1', zone: 'Distribution & Finished Goods', default_printer_id: 4, total_racks: 32, is_active: true },
];

// User Nyata dari tabel `user_produksi` di Database MySQL `produksi`
export const INITIAL_USERS = [
  {
    id: 15,
    name: 'Hartarto',
    username: 'hartarto',
    role: 'supervisor', // Memiliki hak approval tertinggi
    divisi: 'Direksi',
    badge: 'Direksi PT Unison Industrial Indonesia',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&q=80',
    assigned_warehouse: 'ALL',
    is_active: true,
    is_direksi: true,
  },
  {
    id: 13,
    name: 'Bobby',
    username: 'bobby',
    role: 'supervisor', // Memiliki hak approval tertinggi
    divisi: 'Direksi',
    badge: 'Direksi PT Unison Industrial Indonesia',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&q=80',
    assigned_warehouse: 'ALL',
    is_active: true,
    is_direksi: true,
  },
  {
    id: 25,
    name: 'cseon',
    username: 'cseon',
    role: 'admin',
    divisi: 'Admin / IT',
    badge: 'System Administrator (IT)',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&q=80',
    assigned_warehouse: 'ALL',
    is_active: true,
  },
  {
    id: 22,
    name: 'Mr. Chen',
    username: 'mrchen',
    role: 'supervisor',
    divisi: 'Produksi',
    badge: 'Kepala / Supervisor Produksi',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&q=80',
    assigned_warehouse: 'ALL',
    is_active: true,
  },
  {
    id: 28,
    name: 'Kirana',
    username: 'kirana',
    role: 'operator',
    divisi: 'Gudang',
    badge: 'Operator Gudang (Divisi Gudang)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&q=80',
    assigned_warehouse: 'U2 GUDANG2',
    is_active: true,
  },
  {
    id: 24,
    name: 'Rangga',
    username: 'rangga',
    role: 'operator',
    divisi: 'Produksi',
    badge: 'Operator Lapangan (Divisi Produksi)',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&q=80',
    assigned_warehouse: 'U2 GUDANG3',
    is_active: true,
  },
  {
    id: 19,
    name: 'Hari',
    username: 'hari',
    role: 'operator',
    divisi: 'Produksi',
    badge: 'Operator Lapangan (Divisi Produksi)',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&q=80',
    assigned_warehouse: 'U2 GUDANG1',
    is_active: true,
  },
  {
    id: 1,
    name: 'Admin',
    username: 'admin',
    role: 'admin',
    divisi: 'Admin',
    badge: 'Super Administrator',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&q=80',
    assigned_warehouse: 'ALL',
    is_active: true,
  },
];

export const INITIAL_LOCATIONS = WAREHOUSES.map((w) => ({
  id: w.id,
  code: w.code,
  warehouse: w.name,
  zone: w.zone,
  description: `${w.name} • ${w.zone}`,
  default_printer_id: w.default_printer_id,
  is_active: w.is_active,
}));

// Daftar Printer Thermal LAN & Kantor
export const INITIAL_PRINTERS = [
  {
    id: 1,
    name: 'Printer Meja Operator Gudang U2',
    type: 'DESK_OPERATOR',
    ip: '192.168.1.50',
    port: 9100,
    protocol: 'RAW TCP (Socket)',
    location_desc: 'Meja Kerja Operator Depan Lorong U2',
    paper_width: '80mm ESC-POS',
    is_active: true,
    status: 'ONLINE',
    ping_ms: 12,
  },
  {
    id: 2,
    name: 'Printer Meja Kantor Direksi & SPV (IP 1.140)',
    type: 'OFFICE_SPV',
    ip: '192.168.1.140',
    port: 9100,
    protocol: 'RAW TCP (Socket)',
    location_desc: 'Ruang Kantor Direksi & Supervisor WMS',
    paper_width: '80mm ESC-POS',
    is_active: true,
    status: 'ONLINE',
    ping_ms: 8,
  },
  {
    id: 3,
    name: 'Printer Meja Admin Gudang Jaya',
    type: 'OFFICE_SPV',
    ip: '192.168.1.51',
    port: 9100,
    protocol: 'RAW TCP (Socket)',
    location_desc: 'Pos Admin Logistik Gudang Jaya',
    paper_width: '80mm ESC-POS',
    is_active: true,
    status: 'ONLINE',
    ping_ms: 18,
  },
  {
    id: 4,
    name: 'Printer Mobile Bluetooth Pinggang Operator',
    type: 'MOBILE_PORTABLE',
    ip: '192.168.1.52',
    port: 9100,
    protocol: 'RAW TCP / Bluetooth RFCOMM',
    location_desc: 'Dibawa Operator di Troli / Pinggang',
    paper_width: '58mm ESC-POS',
    is_active: true,
    status: 'ONLINE',
    ping_ms: 25,
  },
];

// Master Fasteners Nyata dari Tabel `item` Database MySQL `produksi`
export const INITIAL_PRODUCTS = [
  {
    id: 1,
    sku: 'AB6C50',
    barcode: '8992001001001',
    name: 'BAUT 3/8 x 50 CEMET (Hex Head Bolt)',
    description: 'Baut kepala segi enam material cemet steel untuk struktur mesin industri',
    category: 'Baut Hexagon',
    thread_spec: '3/8" x 50 mm',
    unit: 'PCS',
    pack: 'KARUNG',
    items_per_pack: 1000,
    status: 'active',
    photo_url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&q=80',
    stock_system: 8500,
    warehouse_code: 'U2 GUDANG3',
    rack_code: 'RAK-B-03',
    shelf_tier: 'Tingkat 2 (Baris B)',
    bin_code: 'BIN-3B',
    created_by: 1,
    approved_by: 15,
    approved_by_name: 'Hartarto (Direksi)',
    approved_at: '2026-09-01 08:00:00',
    rejection_reason: null,
    created_at: '2026-09-01 07:30:00',
    updated_at: '2026-09-01 08:00:00',
  },
  {
    id: 2,
    sku: 'AB6102',
    barcode: '8992001001002',
    name: 'Stud Bolt 3/8" x 4" + 2 Mur Hex Nut',
    description: 'Baut tanam stud bolt ulir penuh lengkap dengan 2 mur hex galvanis tahan korosi',
    category: 'Mur / Hex Nut',
    thread_spec: '3/8" x 4 Inch',
    unit: 'SET',
    pack: 'PETI',
    items_per_pack: 250,
    status: 'active',
    photo_url: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=400&q=80',
    stock_system: 3200,
    warehouse_code: 'U2 GUDANG2',
    rack_code: 'RAK-A-05',
    shelf_tier: 'Tingkat 1 (Lantai Palet)',
    bin_code: 'BIN-1A',
    created_by: 1,
    approved_by: 15,
    approved_by_name: 'Hartarto (Direksi)',
    approved_at: '2026-09-01 08:00:00',
    rejection_reason: null,
    created_at: '2026-09-01 07:30:00',
    updated_at: '2026-09-01 08:00:00',
  },
  {
    id: 3,
    sku: 'AB850-',
    barcode: '8992001001003',
    name: 'ANCHOR BOLT 5/8" x 50 cm + Mur Plat',
    description: 'Angkur pondasi heavy duty konstruksi sipil dan tiang baja pabrik',
    category: 'Anchor & Dynabolt',
    thread_spec: '5/8" x 50 cm',
    unit: 'SET',
    pack: 'KARUNG',
    items_per_pack: 50,
    status: 'active',
    photo_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?w=400&q=80',
    stock_system: 1450,
    warehouse_code: 'U2 GUDANG6',
    rack_code: 'RAK-HEAVY-01',
    shelf_tier: 'Area Palet Heavy Stock',
    bin_code: 'BIN-H01',
    created_by: 1,
    approved_by: 13,
    approved_by_name: 'Bobby (Direksi)',
    approved_at: '2026-09-01 08:00:00',
    rejection_reason: null,
    created_at: '2026-09-01 07:30:00',
    updated_at: '2026-09-01 08:00:00',
  },
  {
    id: 4,
    sku: 'AB1040',
    barcode: '8992001001004',
    name: 'PEN PIN 1/8 x 40 mm Carbon Steel',
    description: 'Pin pengunci dowel presisi perakitan alat berat dan sambungan hidrolik',
    category: 'Sekrup & Tapping',
    thread_spec: '1/8" x 40 mm',
    unit: 'PCS',
    pack: 'CARTON',
    items_per_pack: 12000,
    status: 'active',
    photo_url: 'https://images.unsplash.com/photo-1618090584176-7132b9911657?w=400&q=80',
    stock_system: 24000,
    warehouse_code: 'U2 GUDANG1',
    rack_code: 'RAK-C-02',
    shelf_tier: 'Tingkat 3 (Kotak Karton)',
    bin_code: 'BIN-2C',
    created_by: 1,
    approved_by: 15,
    approved_by_name: 'Hartarto (Direksi)',
    approved_at: '2026-09-01 08:00:00',
    rejection_reason: null,
    created_at: '2026-09-01 07:30:00',
    updated_at: '2026-09-01 08:00:00',
  },
  {
    id: 5,
    sku: 'UNS-WSH-M08-PLT',
    barcode: '8992001001005',
    name: 'Ring Plat Flat Washer M8 Tebal 1.5 mm Galvanis',
    description: 'Cincin plat ring pelapis baut penyebar beban permukaan kerja',
    category: 'Ring Plat & Washer',
    thread_spec: 'M8 x 1.5 mm',
    unit: 'PCS',
    pack: 'KARUNG',
    items_per_pack: 5000,
    status: 'pending',
    photo_url: 'https://images.unsplash.com/photo-1589792905706-7b4bf37d2fbf?w=400&q=80',
    stock_system: 0,
    proposed_qty: 4500,
    proposed_location: 'U2 GUDANG2',
    warehouse_code: 'U2 GUDANG2',
    rack_code: 'RAK-A-08',
    shelf_tier: 'Tingkat 2 (Karung Stok Baru)',
    bin_code: 'BIN-8A',
    created_by: 28,
    created_by_name: 'Kirana (Operator Gudang)',
    approved_by: null,
    approved_at: null,
    rejection_reason: null,
    created_at: '2026-09-19 14:10:00',
    updated_at: '2026-09-19 14:10:00',
    notes: 'Ditemukan 9 karung stok baru di rak lorong 4 U2 GUDANG2 belum terdata di sistem.',
  },
];

export const INITIAL_STOCK_SESSIONS = [
  {
    id: 1,
    location_id: 2,
    warehouse_code: 'U2 GUDANG2',
    operator_id: 28,
    operator_name: 'Kirana',
    started_at: '2026-09-19 13:45:00',
    finished_at: null,
    sync_status: 'synced',
    device_id: 'ZEBRA-TC26-WMS-UNISON01',
    notes: 'Opname rutin lorong rak Mur & Stud Bolt',
  },
];

export const INITIAL_STOCK_DETAILS = [
  {
    id: 1,
    session_id: 1,
    product_id: 2,
    product_name: 'Stud Bolt 3/8" x 4" + 2 Mur Hex Nut',
    barcode: '8992001001002',
    warehouse_code: 'U2 GUDANG2',
    rack_code: 'RAK-A-05',
    qty_system: 3200,
    qty_physical: 3180,
    variance: -20,
    note: '20 set dialokasikan ke QC pemeriksaan ulir',
    created_at: '2026-09-19 13:50:12',
  },
];

export const INITIAL_AUDIT_LOGS = [
  {
    id: 1,
    user_id: 25,
    user_name: 'cseon (Admin)',
    action: 'login',
    entity_type: 'user_session',
    entity_id: 25,
    old_value: null,
    new_value: { role: 'admin', ip: '192.168.1.140' },
    ip_address: '192.168.1.140',
    created_at: '2026-09-19 08:00:00',
    description: 'Admin cseon inisialisasi master database produksi PT Unison Industrial Indonesia',
  },
  {
    id: 2,
    user_id: 28,
    user_name: 'Kirana (Operator)',
    action: 'print',
    entity_type: 'printer_socket',
    entity_id: 2,
    old_value: null,
    new_value: { target: '192.168.1.140:9100 (Meja Kantor Direksi)', barcode: '8992001001002' },
    ip_address: '192.168.1.105',
    created_at: '2026-09-19 13:52:00',
    description: 'Remote print dari tengah lorong rak ke Printer Meja Kantor Direksi (192.168.1.140:9100)',
  },
];

// Quick barcode presets for interactive testing
export const QUICK_BARCODES = [
  // Fasteners Scans
  { barcode: '8992001001001', type: 'product', label: 'BAUT 3/8 x 50 CEMET (Di U2 GUDANG3)', status: 'active' },
  { barcode: '8992001001001|LOT-2609A|2497|2026-09-19', type: 'product', label: 'QR 2D: BAUT 3/8 (Lot: 2609A | Qty: 2497)', status: 'active' },
  { barcode: '8992001001002', type: 'product', label: 'Stud Bolt 3/8" x 4" (Di U2 GUDANG2)', status: 'active' },
  { barcode: '8992001001003', type: 'product', label: 'ANCHOR BOLT 5/8" (Di U2 GUDANG6)', status: 'active' },
  { barcode: '8992001001004', type: 'product', label: 'PEN PIN 1/8 x 40 mm (Di U2 GUDANG1)', status: 'active' },
  { barcode: '8992001001005', type: 'product', label: 'Ring Plat Washer M8 (Pending di U2 GUDANG2)', status: 'pending' },
  { barcode: '8999999000888', type: 'product', label: 'Baut Flange Hex M14 x 45 (Baru / Belum Terdaftar)', status: 'unregistered' },

  // Warehouses
  { barcode: 'U2 GUDANG1', type: 'rack', label: 'U2 GUDANG1 (Finishing)', location_id: 1 },
  { barcode: 'U2 GUDANG2', type: 'rack', label: 'U2 GUDANG2 (Mur Storage)', location_id: 2 },
  { barcode: 'U2 GUDANG3', type: 'rack', label: 'U2 GUDANG3 (Baut Hex)', location_id: 3 },
  { barcode: 'U2 GUDANG4', type: 'rack', label: 'U2 GUDANG4 (Stainless)', location_id: 4 },
  { barcode: 'U2 GUDANG5', type: 'rack', label: 'U2 GUDANG5 (Galvanis)', location_id: 5 },
  { barcode: 'U2 GUDANG6', type: 'rack', label: 'U2 GUDANG6 (Heavy Peti)', location_id: 6 },
  { barcode: 'U2 F29', type: 'rack', label: 'U2 F29 (Machining)', location_id: 7 },
  { barcode: 'U2 UCP', type: 'rack', label: 'U2 UCP (Central QC)', location_id: 8 },
  { barcode: 'GUDANG JAYA', type: 'rack', label: 'GUDANG JAYA (Distribusi)', location_id: 9 },
  { barcode: 'D30', type: 'rack', label: 'D30 (Raw Wire Rod)', location_id: 10 },
  { barcode: 'U1', type: 'rack', label: 'U1 (Finished Goods)', location_id: 11 },
];
